######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 9 20:25:07 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ga.cpp
